version: '3'

services:
  database:
    container_name: database
    image: mysql:${DATABASE_VERSION:-8.0}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_DB:-eco}
      MYSQL_USER: ${DATABASE_USER:-user}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-pass}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin
    environment:
      # MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
      PMA_PORT: 3306
      # PMA_USER: ${DATABASE_USER:-user}
      # PMA_PASSWORD: ${DATABASE_PASSWORD:-pass}
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - database
    ports:
      - '8081:80'

  php:
    container_name: php
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
volumes:
  mysql_data:
