controllers:
    resource: '../src/Controller/*'
    type: annotation
    # exclude: 
    #     - '../src/Controller/SecurityController.php'
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%' 

homepage:
    path: /{_locale}
    controller: App\Controller\HomeController::home
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

app_logout:
    path: /logout
    name_prefix: app_
    methods: GET
    controller: App\Controller\SecurityController::logout